### ISSUE TITLE
Automatic build in Docker Hub is not working

### ISSUE THREAD

**Issue by egeland** [kube-aws/kube-spot-termination-notice-handler#12]
I think there's a permissions issue - maybe I don't have the right access level to set up the automatic build?

Can someone with access to the `Settings` for this repo please check if there's an integration with `Docker` set up? Alternatively, bump my access so I can fix it. :smiley: 

We need one set up to trigger the builds.
See https://hub.docker.com/r/kubeaws/kube-spot-termination-notice-handler/~/settings/automated-builds/

**Comment by kylegato** [comment]
Thanks for finding this @egeland - Unfortunately I do not have the required access so we will have to wait for @mumoshu

**Comment by egeland** [comment]
I still don't seem to have the `Settings` option in this github repo..

**Comment by egeland** [comment]
Yes, thank you - I've connected the Docker Hub with this repo, and triggered a build by pushing a tag.
I believe it's now working correctly. :grin:

**Comment by mumoshu** [comment]
Awesome! Thanks a lot for your effort 👍
