### ISSUE TITLE
1.13.7-1 image not in dockerhub

### ISSUE THREAD

**Issue by bzuelke** [kube-aws/kube-spot-termination-notice-handler#28]
Not really an issue but noticed when deploying this that the most recent image is not actually in docker hub. I created my own image for the time being but wanted to note that it's not building these images on tag. 

https://hub.docker.com/r/kubeaws/kube-spot-termination-notice-handler/tags

**Comment by egeland** [comment]
Yeah, I've had some issues trying to get the auto-build set up (again, after docker hub changes).
I'll do a manual build, so we have the image there.

**Comment by egeland** [comment]
And done!
