### ISSUE TITLE
General question, why no need to authenticate `kubectl`?

### ISSUE THREAD

**Issue by left4taco** [kube-aws/kube-spot-termination-notice-handler#33]
This might be a stupid but short question. In the script and dockerfile I don't see anyplace where the user enters the credentials of the cluster, yet still `kubectl` is able to drain a node. What kind of authentication is behind this? Is it using some intrinsic k8s feature? Please educate me. 

Thanks.

**Comment by edify42** [comment]
The README suggests deploying the app via helm `helm install stable/k8s-spot-termination-handler`.

The pod itself runs under a serviceaccount with the k8s permission to create pod/eviction resources, which is what is required for the `kubectl drain node` command.

If you inspect the helm chart, you'll find what I'm talking about :)

**Comment by left4taco** [comment]
@edify42 Thanks Ted. That's really helpful.
