### ISSUE TITLE
this project is still running?

### ISSUE THREAD

**Issue by cpanato** [kube-aws/kube-spot-termination-notice-handler#46]
This project is active? if yes, I would like to contribute. saw the version is quite older.

Let me know if need help here or I should use another tool

thanks!

**Comment by egeland** [comment]
We're still using this, but with the open question ( #36 ) of whether this project can be replaced with a more official one..
Ping me with your PRs if you have contributions! 👍

**Comment by cpanato** [comment]
ok cool thanks!!
